# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LeBonCoinTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LeBonCoinTest
  pod 'Alamofire', '~> 4.7'
  
  target 'LeBonCoinTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LeBonCoinTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
